### ISSUE TITLE
Error when running the  simulation

### ISSUE THREAD

**Issue by danieasv** [lajoiepy/robust_distributed_slam_simulation#1]
Thanks for a great guide. 
When I run the Argos simulator `argos3 -c robust_distributed_slam_random_walk.argos` with x11docker it throws an error after a while saying: 
`QXcbConnection: XCB error: 13 (BadGC), sequence: 601, resource id: 0, major code: 72 (PutImage), minor code: 0`  
`vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)`

Have you experienced this before? I`m running Ubuntu 18.04 with the latest argos3 version (note that the old installation link in the Dockerfile, line 53 was broken).

**Comment by lajoiepy** [comment]
Oh god, I am really sorry it took so long, I was not able to reproduce the bug and I forgot about it. However, it came up again a few days ago and I figured it out.
The code should create a folder named `datasets` inside the HOST_FOLDER (used for logs) that is shared with the container, but this seems to fail in your case.
So,  I suggest you create that folder (`datasets`) manually inside your log folder. I updated the documentation about this.
Here is a link to another closed issue on the same topic: https://github.com/MISTLab/DOOR-SLAM/issues/3
